version: '3.8'

services:    
  create-update:
    build:
      context: ./CreateAndUpdate
   
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=<IP-ADDR>
      - DB_PORT=5433
      - RABBITMQ_HOST=<IP-ADDR>
      - RABBITMQ_PORT=5672

   

  health-manager:
    build:
      context: ./health-check-service
   
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=<IP-ADDR>
      - DB_PORT=5433
      - RABBITMQ_HOST=<IP-ADDR>
      - RABBITMQ_PORT=5672
    

  order-validator:
    build:
      context: ./order-validation-service
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=<IP-ADDR>
      - DB_PORT=5433
      - RABBITMQ_HOST=<IP-ADDR>
      - RABBITMQ_PORT=5672


    
  inventory-manager:
    build:
      context: ./product-managment-service
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=<IP-ADDR>
      - DB_PORT=5433
      - RABBITMQ_HOST=<IP-ADDR>
      - RABBITMQ_PORT=5672
    ports:
      - "8501:8501"
    



