version: '3.8'

services:    
  create-update:
    build:
      context: ./CreateAndUpdate
   
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=10.30.201.82
      - DB_PORT=5433
      - RABBITMQ_HOST=10.30.201.82
      - RABBITMQ_PORT=5672

  rabbit:
    image: rabbitmq
    ports:
      - "5679:5672"
      - "15679:15672"

  potgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5839:5432"

  frontend:
    image: node:14
   

  health-manager:
    build:
      context: ./health-check-service
   
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=10.30.201.82
      - DB_PORT=5433
      - RABBITMQ_HOST=10.30.201.82
      - RABBITMQ_PORT=5672
    

  order-validator:
    build:
      context: ./order-validation-service
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=10.30.201.82
      - DB_PORT=5433
      - RABBITMQ_HOST=10.30.201.82
      - RABBITMQ_PORT=5672


    
  inventory-manager:
    build:
      context: ./product-managment-service
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=10.30.201.82
      - DB_PORT=5433
      - RABBITMQ_HOST=10.30.201.82
      - RABBITMQ_PORT=5672
    ports:
      - "8501:8501"
    



