

services:

    rabbit-mq:

          image: rabbitmq:3
          ports:
            - 5672:5672
          # environment:
          #       RABBITMQ_DEFAULT_USER: user  
          #       RABBITMQ_DEFAULT_PASS: password

    rabbit-mq-console:
          image: rabbitmq:3-management

          environment:
                RABBITMQ_DEFAULT_USER: user  
                RABBITMQ_DEFAULT_PASS: password


    db:
          image: postgres

          environment:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: password
                POSTGRES_DB: DBT
          
          ports:
                 - 5432:5432
            

          depends_on:
                - rabbit-mq
    
    db-admin:

          image: dpage/pgadmin4
          environment: 
                PGADMIN_DEFAULT_EMAIL: test@gmail.com
                PGADMIN_DEFAULT_PASSWORD: password

          ports: 
                - 5050:80 
          depends_on: 
                - db